object Versions {

    const val mockk: String = "1.12.5"
    const val room ="2.4.2"
    const val daggerHilt = "2.38.1"
    const val hiltPath = "2.38.1"
    const val composeNavigation = "2.5.0-alpha03"
    const val espressoTest: String = "3.4.0"
    const val androidTest: String = "1.1.3"
    const val composeActivity ="1.4.0"
    const val lifeCycle = "2.4.1"
    const val androidCore = "1.7.0"
    const val gradlePlugin = "7.2.1"
    const val ktLintGradle = "10.0.0"
    const val ktLint = "0.34.2"
    const val kotlin = "1.6.10"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val jUnit = "4.+"
    const val compose= "1.1.1"
    const val retrofit = "2.6.2"
    const val retrofitCoroutines = "0.9.2"
    const val retrofitGson = "2.6.2"
    const val scalarsAdapter = "2.9.0"
    const val gson = "2.8.5"
    const val okHttp = "4.10.0"
    const val constraintLayoutCompose = "1.0.1"
    const val coil = "2.2.0"

}
